# Generated by Django 4.2 on 2025-11-22 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_author_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
