# Generated by Django 4.2 on 2025-11-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_author_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('news', 'News'), ('article', 'Article')], default='news', max_length=10),
        ),
    ]
